/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balances"
      | "deposit"
      | "getEffectiveLimits"
      | "maxWithdrawalsPerAccount"
      | "owner"
      | "ping"
      | "setMyTokenLimits"
      | "setTokenLimits"
      | "totalWithdrawn"
      | "userLimitsSet"
      | "userMaxWithdrawalsPerAccount"
      | "userWithdrawalLimitPerAccount"
      | "withdraw"
      | "withdrawTo"
      | "withdrawalCount"
      | "withdrawalLimitPerAccount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "MyTokenLimitsSet"
      | "Pinged"
      | "TokenLimitsSet"
      | "Withdrawn"
      | "WithdrawnTo"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEffectiveLimits",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdrawalsPerAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMyTokenLimits",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenLimits",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLimitsSet",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMaxWithdrawalsPerAccount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userWithdrawalLimitPerAccount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTo",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalCount",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalLimitPerAccount",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdrawalsPerAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMyTokenLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userLimitsSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMaxWithdrawalsPerAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userWithdrawalLimitPerAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalLimitPerAccount",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MyTokenLimitsSetEvent {
  export type InputTuple = [
    account: AddressLike,
    token: AddressLike,
    maxWithdrawals: BigNumberish,
    maxTotalWithdrawable: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    token: string,
    maxWithdrawals: bigint,
    maxTotalWithdrawable: bigint
  ];
  export interface OutputObject {
    account: string;
    token: string;
    maxWithdrawals: bigint;
    maxTotalWithdrawable: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PingedEvent {
  export type InputTuple = [caller: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [caller: string, timestamp: bigint];
  export interface OutputObject {
    caller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLimitsSetEvent {
  export type InputTuple = [
    token: AddressLike,
    maxWithdrawals: BigNumberish,
    maxTotalWithdrawable: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    maxWithdrawals: bigint,
    maxTotalWithdrawable: bigint
  ];
  export interface OutputObject {
    token: string;
    maxWithdrawals: bigint;
    maxTotalWithdrawable: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnToEvent {
  export type InputTuple = [
    user: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, recipient: string, amount: bigint];
  export interface OutputObject {
    user: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockVault extends BaseContract {
  connect(runner?: ContractRunner | null): MockVault;
  waitForDeployment(): Promise<this>;

  interface: MockVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  getEffectiveLimits: TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [
      [bigint, bigint] & {
        maxWithdrawals: bigint;
        maxTotalWithdrawable: bigint;
      }
    ],
    "view"
  >;

  maxWithdrawalsPerAccount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  setMyTokenLimits: TypedContractMethod<
    [
      token: AddressLike,
      maxWithdrawals: BigNumberish,
      maxTotalWithdrawable: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setTokenLimits: TypedContractMethod<
    [
      token: AddressLike,
      maxWithdrawals: BigNumberish,
      maxTotalWithdrawable: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalWithdrawn: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;

  userLimitsSet: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  userMaxWithdrawalsPerAccount: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  userWithdrawalLimitPerAccount: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<
    [amount: BigNumberish, sessionKeyId: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawTo: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike, sessionKeyId: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawalCount: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;

  withdrawalLimitPerAccount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getEffectiveLimits"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [
      [bigint, bigint] & {
        maxWithdrawals: bigint;
        maxTotalWithdrawable: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxWithdrawalsPerAccount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMyTokenLimits"
  ): TypedContractMethod<
    [
      token: AddressLike,
      maxWithdrawals: BigNumberish,
      maxTotalWithdrawable: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenLimits"
  ): TypedContractMethod<
    [
      token: AddressLike,
      maxWithdrawals: BigNumberish,
      maxTotalWithdrawable: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalWithdrawn"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userLimitsSet"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "userMaxWithdrawalsPerAccount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userWithdrawalLimitPerAccount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amount: BigNumberish, sessionKeyId: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawTo"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike, sessionKeyId: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawalCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawalLimitPerAccount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "MyTokenLimitsSet"
  ): TypedContractEvent<
    MyTokenLimitsSetEvent.InputTuple,
    MyTokenLimitsSetEvent.OutputTuple,
    MyTokenLimitsSetEvent.OutputObject
  >;
  getEvent(
    key: "Pinged"
  ): TypedContractEvent<
    PingedEvent.InputTuple,
    PingedEvent.OutputTuple,
    PingedEvent.OutputObject
  >;
  getEvent(
    key: "TokenLimitsSet"
  ): TypedContractEvent<
    TokenLimitsSetEvent.InputTuple,
    TokenLimitsSetEvent.OutputTuple,
    TokenLimitsSetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnTo"
  ): TypedContractEvent<
    WithdrawnToEvent.InputTuple,
    WithdrawnToEvent.OutputTuple,
    WithdrawnToEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "MyTokenLimitsSet(address,address,uint256,uint256)": TypedContractEvent<
      MyTokenLimitsSetEvent.InputTuple,
      MyTokenLimitsSetEvent.OutputTuple,
      MyTokenLimitsSetEvent.OutputObject
    >;
    MyTokenLimitsSet: TypedContractEvent<
      MyTokenLimitsSetEvent.InputTuple,
      MyTokenLimitsSetEvent.OutputTuple,
      MyTokenLimitsSetEvent.OutputObject
    >;

    "Pinged(address,uint256)": TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
    Pinged: TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;

    "TokenLimitsSet(address,uint256,uint256)": TypedContractEvent<
      TokenLimitsSetEvent.InputTuple,
      TokenLimitsSetEvent.OutputTuple,
      TokenLimitsSetEvent.OutputObject
    >;
    TokenLimitsSet: TypedContractEvent<
      TokenLimitsSetEvent.InputTuple,
      TokenLimitsSetEvent.OutputTuple,
      TokenLimitsSetEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "WithdrawnTo(address,address,uint256)": TypedContractEvent<
      WithdrawnToEvent.InputTuple,
      WithdrawnToEvent.OutputTuple,
      WithdrawnToEvent.OutputObject
    >;
    WithdrawnTo: TypedContractEvent<
      WithdrawnToEvent.InputTuple,
      WithdrawnToEvent.OutputTuple,
      WithdrawnToEvent.OutputObject
    >;
  };
}
