/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockVault } from "./MockVault";
export * as factories from "./factories";
export { MockVault__factory } from "./factories/MockVault__factory";
